---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-app-user
  namespace: fintech-databases
spec:
  encryptedData:
    password: AgCktRubMX5vgpSdBhuAHHbKznFsBF8fltcCy9MM/fLLjCDbl8hxYYlSdCONwS9DpWSbpSkhXarYt3CD22ZqQMsMjzVTOSppfhhqAba5cxj7++wQhlS+t5bfA2oZpfm6SU2qYprpGzMxb//eq14SAariS0mLQ+bHC8wisgm2GPcuSfNniWyVsEGk4pOTbsd0o17nOMEvdkwM+oB6C/5+yUe6Uda42ARMHQuopNy9+hbVmcsR4D2ZGxsVNhNt/jPYeM8Oro2QCv1/JNXFVXXkDpEF6C1+hZwjsn3R/gK9yw6SgsInP0UFxGyFOKviW3aoBzQ9kQouDF8bJtmAXUBK5hPeaiYWI4hn6IIN8q2udHevx3Xi6u53pSZdW51hI+BF9Ml3lRX+YOHvIE2RjchHxJzJAQN+bsAFJoJC4NuzShmwMla+h92sjLvsHoONA0XAS5XeW+OTKoC8S3sSx2L22f0NdX8y/Y+c5FF+FIQfBF2WgRlNWWehJ+gGFcmtTtBC7Acu6Hc4CWtUG45Cw0eVmVuhRsZmoDNrFvHqoVwWSNKFlWXBct8wLh4XJ25qnjqiwAJAoOtVDMBnhAHjZ6sjcezPqM6jHJl1rvcALnuRd+dW7n7AFXoOzTVivOmtzO6R2Gom3gTnaQSUEXvrBBMXd0Jb9/JgjK0oOMRcDOHFzxys0cE25ShXj2Y45gdKPNeO0Jr8qHLn+QH8fystStjQRFkbuQ==
    username: AgBYuNOxxyazGqMCtjaqvoe5fNblWMZJz9rmCAabnNOgsr0+H3MqJEkMW15+4c612j1U2rqEEv6gnBO10PRHG2XdYE5h7a1T1svTI26l4VC7AkLHGZgDvFAd28Ddsub2w9gqYOk4raaNiY0pSiuHHr+j9l2SniuQR8FhVUANfG2FwuLwzlXAHlmT5+8SC6f7dftrd8GJWGPvqANhS/07vacSIgkCfy+ZfvOOAh0i8Mt6q6EsvPFHz3yNVkBgmee/E70a5UQ5oBsvqYCpmnd4hSehwpv1sWF/LTM3/5NML/ojKvkmLQyssN3j1bPUK+3H9RQur2VPmP0KUaYXedCu8WzEXIhYSvxIUR5U9FNuysDQBUv+BhkWzf2ZcwsDUB6PsVKT9G0ExVA6h/gZ/P7NkfeckoNpECTAEwCbGKofoeEFS9D/s8CpObfozyUHQrl14YVDUi+haYx/m1vuMty2g9nvFOPKFfebSKx92fe0lrWiCehCcSI+lQRF/ihceWWAzJfthNuOpRQTHo425qgT1ngCqRxlZwHT6T6qbJAQhKUAZjIRrlpc6Vei1HELeNAGNSDOOG1IKzsJbkfFoOqECk9jL5d2Tr1yeELSwTVy3Xw92ZLBe01NxfaHlzBaELe7gpn3xwVcIi+Nto89V6x82S6sXmEdKpo/Iz3CMR68i/9yovYJMQSN7w6y58Y+yms95WGCaAelmjpqGH26e3Ux
  template:
    metadata:
      creationTimestamp: null
      name: postgres-app-user
      namespace: fintech-databases
    type: kubernetes.io/basic-auth
