---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-backup-secret
  namespace: fintech-databases
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAhekYFLOx5ePwYcca+9IIoubn0TuVi3u+HVv0BdEKGVyO/CEGYnq6+ub/xM9U989M3RDaBx/SnZ4UjMNTLkDF+IBvyQqIYbYFTaHAcAdJ1QEADML4AFE4NpTAmMLhHRjDBRFTUx2a/Z2HLo6UbAKLEPI1hHjUfUIrJNQ/4bIXXXpKYskSRxFEQxb06CezyE8TF+E3whqCXCl+r6/ulpefczGSQviZcR+9zMWUV+Unw+bIPRg3KEWXySxWhJfPTw0cwEtKKcsyPQTbYaa39idkh3SENIKSASwSsfZc3nnv5GNVe7RBwk7uPUaGC2fEWCyvMaO7HZAM8o/jIoYJ1TC9UpDYI0dO8RnYbk2t69v+dLsSiDgelZOQLsItchVszmhaEZj9+jCsTTTKgX0InUta+v3aIPn0TEHL9mEgUncF9V7n6rajr+aRGZ2KYUPS5D2yJ/bIZeypDSqZVWFdq5eMWctiCvjeNompotWBqGpHhdsz2N4ZUxxqevSiaxIyhi6JCpfy7k99hfSICogzMd9CfNMGpf/qMEISxS30e5UQJq6hQwooU6nKWPK1ahuCJ1vlVhC7WGniVS1IbzOrdc7XGfhRDfxLdWfs9MSAjTq/+GBMyYKyxjJ/DxErljBhiCfFgwzSMUxDap6hSNlbaoKZJ5f1JMPnGM7WMXUwWs1ttjHRcAn0BuvxdkZdU+pCsp+YhHTRb0SrKaoBgDNs2AMml
    ACCESS_SECRET_KEY: AgBW2Z/5T0eHwU5PnMxIchlCxkS7OKzKk72Brd+uw04HHdf9rwyFIXUwMyfSPVM5AIxa/d20ZdgpmMHO8lt9aVjjMntJ8Wup+z7Vx6l9lysA1v7jSRIp/IGyjXuvM9Ogmc0tPeF7a4Uz5i/zmx7anPRplVmlQuUP2e1zKDf0eVnsR4kvVP/HfwAA86Ri2UvQlfx5mj/C+ILKlNsfBKdNPvMHyucZyh06IAzyX51BqJYQgN9t56UsKCv326W/Hh++hJpuZorotZLS3cHo41qbIk+w1cjSHr0Nr0AlHVi8CGoNCo9EJ03kgz8XD76+C2JHhWfzN4dOD5S1C8/cFMQF7zaLxtuqFAL+XXp1Ei7X3TW01IIK5zbZNHiuqOJ6f6sBJom4NOhImA/ECt2R5bukU9Bt22LHK1ddvx0d7gPgZJ/fh4KuhrQ179IHmcEtexUt0T0l6Vl/SSGLkgoDuqiD8TZkXDsAv+lkzE1QhZ19mUBpxBF7YVWWWnVFshfxWThemJE4mch2yS2TvljfxATCoI3VjJDpqugVVSGIv5pQplAoDPj6MzfP6QovETDnGw9w5C9agx2wKfOvgSyyt9t8C79mYCIYJ+A7PTul6p9KUBSXaov0sKY3DpBK24Y/Rq6r1MRUlufgPlEDAwQLo5zbk12pgCQ/TPU1jJWjbtKsn/n/Yhnku0BRHEh394rkiVkClUWUsDNCZokDDS8SaBMT2PYqAAQehPksG5H4
  template:
    metadata:
      creationTimestamp: null
      name: minio-backup-secret
      namespace: fintech-databases
    type: Opaque
