---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-backup-secret
  namespace: fintech-databases
spec:
  encryptedData:
    ACCESS_KEY_ID: AgACLfHc6F91NMo/eUsTkvuFyOZaMYqKSD8qcYMR6aL2ebU307S9hln1gC3B9+f5CtlOKBwDXLShAbO2zXSdwUBY3yvWau8y6hfkVdaCCu30EnXU+QB4Xb26uzkA7ZWB+wac2a41IW7b65Cq52izGsg3dPdjoqShvhSdc3UnpZjbWrlTQlnbtO8NzqOsd501MemCJmQAsF2Mmkd84zc+dol2NdyxfiW1P/EY+7M9RxGP6/kTycSgUS7Q40r7ddPOgbUpVxVITJJnIzOCcM+abBsGXcIz3+Xx1HEoCBJuxrJzqhuojlrsfVwCCUAUhzWCEha1zFS2H8hzgOUO57YRtwhVOx8WU0/t6qJZuJ04Hd330Net5lbQxsaQVLh+WOa/gKFEleY9DFDho8wOiOSarcRhYSLw6ZV8u//KL/Ro/aOYiIE9Zyjb4JDKY4Y3ro5+kM7HYD/PaL6U3RVrhorgquE38sdXDr2tVW9B3D33rqxBSmU/V362MXt398Sx0zXmqWJr/NrG+OShy2Yu/yJHXE1BcCzwM9ofjt+Ht4XIPxsbJgsCm33JaeXy/WzKFSkSUS8ZR+A0u+Zv1TV18D7dMCAj7vVmElgFFQeb8FEHwtEmefaDIqvBwUPr1pcWi1jRGXPvRN2LAAqQeuhnDmkktbgEwjWZWCXlHzIzzrJuXMEVt8DtyzaDR95rgOQRnhp7lqzIBmVDWIblHXY9ETPEH+F+
    ACCESS_SECRET_KEY: AgBd9lhTLjIDYumiX9k9sQwOghOTegKg7w0arAk6zzmoIMflRyE1lQTiBgbGf6TDcGAQ0DjkCMGVvUr8PUbiM4ld5cQMGUZj7rdiKMe58Gk03Q6R8Pi+ILwOmHcdaHKox1KYkl+mNRG9nALq42a/85XrvdCg0DXwDKDy+jf6uewN2euhpkfL+q83/nmQ+0CPOKn5GR1l9ATejxZBrE4pddaQNRb1u5NhnjAbGU4J2JIuWybluXi82AMIVTwPqFvs2O1j3pv1RsF3/QNjxsRv3gnJMef+WHu6Ck40KSrSENUkcACtuJ2mf1b/fnB23z4TU9ElJkYaFmk4CBpZB4714L6G/9MUJ8WNGTrmYsTYhTLkEqZZFT8BvE4Qnace7eGt+rwtsbrQB8YKfPnClGNl9cRZCqRwCwRocPTZRSiVyTkZQTt2L8AissuwOO0ppWHN/6EqifK5xcwmi+X0e2Pk8+uWn9uQF8TntSLBDnDvF6+EUBmrJJvI+n9GEIb8Qfwt+WKsEsqovigmgfn1c2nW3+ObI5T8NVRPwQrnPV+NPf+TIFY58RiPKcNWYgcrPVbSCtSEJ4mTh90cI7txxV9kSQ60l0f6LMYs170ju8l9ld/Y3kiUv/di4RcoO20WqNXGNRMUZVMp+lpBtHmYUX47BMV1jJwcbKLIrC+ZTNk4Mx5auzfh3s+R1P5sCwXVG+V5Wcey8bk1fzuuZajsIV8=
  template:
    metadata:
      creationTimestamp: null
      name: minio-backup-secret
      namespace: fintech-databases
