apiVersion: v1
kind: Namespace
metadata:
  name: fintech-apps
  namespace: fintech
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: apps-quota
  namespace: fintech-apps
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1536Mi
    limits.cpu: "2"
    limits.memory: 3Gi
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: apps-limit-range
  namespace: fintech-apps
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
