---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fintech-db-secret
  namespace: fintech-apps
spec:
  encryptedData:
    db-password: AgCCP5tASkiuVjfG1PXJ7MJEK2UvG8R2VceWQ2bu5Gt4gET9MsDoT/T6KVbSw8+ucF64plK9IyB+jqE71O/5J34kjfU7ZXC7LY90ONGF7hr4/2TY/i5tYpmxw2pjAFX2HemuAfdPP6qp9nysiVmZGVVttC/MTIP/XMIQA5aYd4AJyUpVAXKAsw5TbI+fPoCsKwYMfs9wv2wZr0cVGNbBDGP6cwUvfcFjvXglIsWF5NWfCmQCGqYHTHimAOs3eKSP0/AUJn8WyeLnNwTpjcGQMTpaotxCWSKa7PLRQSiX0/2CdKsQn9vb5SAC1GkgHKhCSRdSxBD/fbJrFZPZ1WKXT5usm6wCaYSKIHi3ehJSh7+opokS8uy9FYleMJkM0l+gnVU/oUFlem/AVdRKwPk9k9QrYvNAgHeBMwWsM9pmggBqZtcNcFuPGnBm+axZV0tTrQvxxub3igGa+9YktSVU8NoAbvZzjo+4db2OtTeJsaSZVdZD37yQS2urYPxvGtxedywSo6HbG50PZ1tAdU02bTqerIbwbMRoXRnolG4b3wkWKTdyeLhKrMseSPVPgOMtsUPOmVWNPPgvTp+rsfNUYc9p6LSurLf1jre5PbyrHWvr8mBkJjM6Ve1TM6bxqmZIGLUMUOsYZzXT/4IkkPQiMoCExF4GmIeT+Q3RP3FdV05kHUOweE8soa0WgwughNj88J5Q5Fg1CuLGU4lVAyI9aESQ8w==
    db-user: AgAw3/VGlXPtK+JDYuqAmizteY4NaUF1wej3xDqqf7IQiyfmDOgu5MDmtaN5oROd+HwnwOpPYWj6mT4UEcOtq26PBkAZa3kjuDW9YxJx9h/cUcF7oUZI31OyNyHpia5A+FYhPtImqW9G79XSN45AKCW9FnIgQ8HANiSbaKUAE+5wML4m4fgJZWQvphS5mBP+4m3onVXydkaP6w69hTAnrIWxT/Smc33YiRex+079RjOI1R0O4g5h1TgPi6OfupO5Y4S2dQBatXi6sQ5610yIkb85CAJYODCWaZhxBMNV7n77X4DnmS08A3Ha5yLzgK35UBpsumzCfsssV4bMXdKWYxbPr5IuyHfvyc5QeFV59Rz5gf4F2hd8sw/pESKKn6aIB+s5l67s9yrmGpU41p8oxetMoMaJtzzc8i79EEiq/u+72P1N55fyaVvP6hY9mebyhyZsHrPiFePPcpWU2lP8ImCMud9Ou8VPgaPMVKS98P0PYsEJJSYoTNYF11Y7ZGocJyM7vK41uu9t2cz6IPpA0qKKsEfuKamO+eXTpefv0gBFYPftH9mdtCccE891ywfhT4Rs/KLFIsez1qfwYuLvuarCZ1OgZh4ph2IaTClzkm37OXTu+LFVjSs73tDbhyhkpkW3taAQ7b+k2bnnYzoNesgajpK+AHM7tPUmoi9MsqzoFjPjMfvcRMjnLh2SrY923ZBrQnqaiRaYqCiL9STE
  template:
    metadata:
      creationTimestamp: null
      name: fintech-db-secret
      namespace: fintech-apps
    type: Opaque
