---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-registry-secret
  namespace: fintech-apps
spec:
  encryptedData:
    .dockerconfigjson: AgAv0Kacm2YXgJWf+FZvKsDPjZm+PQPQRp/yGIG5Yjewr96FZ83smeLkQrQO7X+vcg+UaBz3GWfnByYZ2+RPohiczxBdH6CQ9HbFfVmA+LeWclPK7mY3pFhwvHtw+h48lhGu3eYeY3EchkJypaKilKdGAqUDi3ojhTh8dwmH0YHlF129W7Al5YGrJ3OHR1NsUGftYLarUs9h858qX/jwIe5Dm2yRaHh7HLVPWAWt/aHk0xqjHDTWgbIh7FFm4hnpLiBURNBrTskAqCxyVnKgng87x9eKDtI9Yt/QhShmt4CC18aLXHEwM3TXlJsbDnmitnTe2jJt16ukXmVz19DqQ5no9E03Eb+6OP7jYaV//6wSm+xdMj3hLUW07m5uPUMNhcd9v6bL7DIfpWA9wpvjDrFc8NYYd6FFhBivx5RNV15dkK61rjGlICwDEmutHtv9qJDi0OhSBENNPqGrY0NdKMJwJO4acUyZdFUEeBQu07bo7QBBovEAD1WTHZXBGRVc53O3Q4z/D9fTE5G8EX8EVM0RP+6qae6CewyBTv7FPjhkdPdKBB7nQRICFFXbJQ+Aul4wYp8PYJcPkCVYVyOVAmcZDowR+gDaYr7g9gSq5HAFso4SjB7QT6p/eO7vX1OFDkCgliHBeSdfcZw7yDbZrBZRwrxHtjyjfooQMLYFQbJ/VNMhnsK6rZ8P3it/PnmMV61kqTC6qsjNXyNCLZk28JtHWkoHNieCQMfm3ObtdnwoCbsnMkiGhTMJ9z8C59q7JkNb1ghMDCYUHEPikmoZZfXZckw14c20g0l+buvWjelkNFMi2jP4MaLJ6d4u5osgxpXGtqsYFM3x4sMrw03aKWvv4XGWvnGP+p5rgvvAjN9Ubbc2T0vD8d/DEGBsE+w4qJOVXvQSJQdRJAj3RnYNzrGN3To0kwpde0axXhO9m3wQ5sRDGcbH99tasAOwFcy8MqxG+KQxFjw=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-registry-secret
      namespace: fintech-apps
    type: kubernetes.io/dockerconfigjson
