apiVersion: v1
kind: Namespace
metadata:
  name: fintech-monitoring
  labels:
    tier: monitoring
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: fintech-monitoring
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    persistentvolumeclaims: "5"
    