---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-creds
  namespace: fintech-monitoring
spec:
  encryptedData:
    admin-password: AgCGPabeRWAC7KQ8CvGBxX8PRNbKQLrIBh6ZhCs/2UewJIVaj2QExG01GL9W0QXAtG+58UxoBqvPCOsArVR6KARI//nWowWZnbNbkH/nDSUhF/J6lys1fTeaEU6o/MnaWzJ2taeCq88pWP4omW8d55naY88h/eJEbzA6GhQSMJqgPkb72KLcd96Sv7kZmBPvMk33GaOd0W9xAv211spInZe+XK0xNxpKn69uEXdAbLb8V4vtsQEMoYAYGBf7tvfkm+1krejFKHqplDvng0+1wzHcOyd2TBYhzcn/7rYkmi4elRLEN2bWN56UIjJIWR4FBPaGa1wo/Y1m5zsDzC1XMIQ/pV1bUkabbyOuLSGMiEYsAZ6itYt0YA0LxJwvbF17Ls+HTHEOtknDImMK1+vIbJcnSn2oq/U0DMR5KBpD4VvdS2T7PkeBd6Hb4TF/sg3zX6y6DgM+NSdwLg4HzI47IAHpUrHmOqIvNE4yA1eNmMcv5DPmsh0Ov9mBKYnxgS+13gNIW6aTzL8PLqFsW6pYnuyIP98Px7/h4ly6mZPiwY/LrK6kp4rAiUGA9HLRZ8Ov3XP+2jLoGeFmjXbVW4SNGxvHBrQSkK25QkYJi7VFbfytSg1gdZhU2L6SDfICFJfFS+2ZJCD5KN+D6zaVGHF7AXE+9/UjfHapHBwVPJFnZc2wyVrN2voXbZR9wgu1aSMtYND0n0bNO7G+l9s2fXwt
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-creds
      namespace: fintech-monitoring
    type: Opaque
